### ISSUE TITLE
Periodic Status Frame 3 is not documented

### ISSUE THREAD

**Issue by AaronPinto** [REVrobotics/SPARK-MAX-Documentation#12]
In REVLib version 2022.0.0, the changelog says it "[added the ability to set the rate of periodic frame 3](https://docs.revrobotics.com/sparkmax/software-resources/spark-max-api-information#version-2022.0.0)", but the [Periodic Status Frames documentation](https://docs.revrobotics.com/sparkmax/operating-modes/control-interfaces#periodic-status-frames) doesn't contain any info on frame 3.

If someone could add what status frame 3 contains, that would be really appreciated. Thanks in advance!

**Comment by NoahAndrews** [comment]
Thanks for pointing that out. FYI, status frame 3 contains all of the information for the analog sensor (position, velocity, and voltage).

**Comment by AaronPinto** [comment]
No problem! I'll close this issue now.

**Comment by NoahAndrews** [comment]
I'll leave this open until we actually add the information to the docs

**Comment by AaronPinto** [comment]
Ah good point, sounds good

**Comment by team3572** [comment]
> Thanks for pointing that out. FYI, status frame 3 contains all of the information for the analog sensor (position, velocity, and voltage).

I'm working in reducing CAN utilization. What is Frame 3 used for? What impact might there be if I reduce the reporting to 100 or 200ms in a SparkMax i'm using just as a percent output controller to a motor?

**Comment by AaronPinto** [comment]
If there's no analog sensor plugged into the spark max, then there will be no impact (other than reducing CAN utilization a bit) at all.

**Comment by NoahAndrews** [comment]
@AaronPinto is correct.

**Comment by team3572** [comment]
I'm just the software guy. We are using NEO and NEO 550s (?) on all the SparkMaxs, so is the sensor from those motors analog?
